language: bash
os: windows
services: docker

env:
 global:
   - DOCKER_HUB=willdockerhub
   - ALI_REGISTRY=registry.cn-shenzhen.aliyuncs.com/aliwill

before_script:
  - docker version
  - env | sort

script:
  - |
    (
      set -Eeuo pipefail
      #login
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker login registry.cn-shenzhen.aliyuncs.com -u $ALI_USERNAME  -p $ALI_PASSWORD
       
      #pull image
      docker pull mcr.microsoft.com/windows/servercore:ltsc2019
      docker pull mcr.microsoft.com/dotnet/framework/runtime:4.8
      
      #tag image
      docker tag mcr.microsoft.com/windows/servercore:ltsc2019 registry.cn-shenzhen.aliyuncs.com/windows-baseos/windows-servercore:ltsc2019
      docker tag mcr.microsoft.com/dotnet/framework/runtime:4.8 registry.cn-shenzhen.aliyuncs.com/windows-baseos/dotnet-framework-runtime:4.8
   
      #push image
      docker push registry.cn-shenzhen.aliyuncs.com/windows-baseos/windows-servercore:ltsc2019
      docker push registry.cn-shenzhen.aliyuncs.com/windows-baseos/dotnet-framework-runtime:4.8
    )

after_script:
  - docker images
