language: bash
os: windows
services: docker

env:
 global:
   - DOCKER_HUB=willdockerhub
   - ALI_REGISTRY=registry.cn-shenzhen.aliyuncs.com/aliwill

before_script:
  - docker version
  - env | sort
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker login registry.cn-shenzhen.aliyuncs.com -u $ALI_USERNAME  -p $ALI_PASSWORD

script:
  - |
    (
      set -Eeuo pipefail
      set -x
       
      #pull image
      docker pull mcr.microsoft.com/dotnet/framework/runtime:3.5
 
      #tag image
      docker tag mcr.microsoft.com/dotnet/framework/runtime:3.5 registry.cn-shenzhen.aliyuncs.com/windows-baseos/dotnet-framework-runtime:3.5
   
      #push image
      docker push registry.cn-shenzhen.aliyuncs.com/windows-baseos/dotnet-framework-runtime:3.5
    )

after_script:
  - docker images
