language: bash

services:
  - docker

env:
  global:
    #change the registry name and username/password to yourself's.
    - DOCKER_HUB=willdockerhub
    - ALI_REGISTRY=registry.cn-shenzhen.aliyuncs.com/images_mirror

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker login $ALI_REGISTRY -u $ALI_USERNAME  -p $ALI_PASSWORD

jobs:
  include:
    - stage: test
      script:
        - |
        for image in $(cat img-list.txt)
        do
          image_name=${image##*/}
          docker pull $image
          docker tag $image $DOCKER_HUB/$image_name
          docker push $DOCKER_HUB/$image_name
        done
      script:
        - |
        for image in $(cat img-list.txt)
        do
          image_name=${image##*/}
          docker pull $image
          docker tag $image $ALI_REGISTRY/$image_name
          docker push $ALI_REGISTRY/$image_name
        done 
