language: bash
os: windows
services: docker

env:
 global:
   - DOCKER_HUB=willdockerhub
   - ALI_REGISTRY=registry.cn-shenzhen.aliyuncs.com/windows-baseos

before_script:
  - docker version
  - env | sort

script:
  - |
    (
      set -Eeuo pipefail
      #login
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker login $ALI_REGISTRY -u $ALI_USERNAME  -p $ALI_PASSWORD
      for image in $(cat img-list.txt)
      do
      	imagename=$(echo $image | awk -F '/' '{print $NF}')
      	docker pull $image
      	docker tag $image $ALI_REGISTRY/$imagename
      	docker tag $image $DOCKER_HUB/$imagename
      	#push to dockerhub
      	docker push $DOCKER_HUB/$imagename
      	#push to aliyun
      	docker push $ALI_REGISTRY/$imagename
      done
    )
