# This workflow will pull docker images from gcr.io quay.io and push it to dockerhub or aliyun registry.
#
# To configure this workflow:
#
# 1. Set up follow variables as your own: 
#    - DOCKER_HUB: dockerhub account name
#    - DOCKER_USERNAME & DOCKER_PASSWORD
#    - ALI_REGISTRY:  aliyun registry url with region
#    - ALI_USERNAME & ALI_PASSWORD
#
# 2. Change the values for the DOCKER_PASSWORD, ALI_PASSWORD  environment variables in travis-ci.com:
#    choose "more options-->settings-->Environment Variables"

os: linux
dist: bionic
language: shell
services: docker

env:
  global:
    - DOCKERHUB_ACCOUNT=willdockerhub
    - ALI_USERNAME=willzhmic@outlook.com
    - ALI_REGISTRY_URL=registry.cn-shenzhen.aliyuncs.com
    - ALI_REGISTRY_NAMESPACE=images_mirror

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$ALI_PASSWORD" | docker login "$ALI_REGISTRY_URL" -u "$ALI_USERNAME" --password-stdin
 
script:
  - |
    echo "start pull retag and push"
    count=$(cat images.txt | wc -l)
    icount=1
    for image in `cat images.txt`
    do
      echo [$icount/$count]: $image
      image_name=${image##*/}
      docker pull $image
      docker tag $image $DOCKERHUB_ACCOUNT/$image_name
      docker tag $image $ALI_REGISTRY_URL/$ALI_REGISTRY_NAMESPACE/$image_name
      
      # push to dockerhub
      docker push $DOCKERHUB_ACCOUNT/$image_name
      
      # push to aliyun registry
      docker push $ALI_REGISTRY_URL/$ALI_REGISTRY_NAMESPACE/$image_name
      ((icount++))
    done

after_script:
  - docker images --format "{{.Repository}}:{{.Tag}}" | grep $ALI_REGISTRY_URL
  - docker images --format "{{.Repository}}:{{.Tag}}" | grep $DOCKERHUB_ACCOUNT
